# Generated by Django 3.0.5 on 2023-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Discription',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.TextField(),
        ),
    ]
