# Generated by Django 3.0.5 on 2023-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20230905_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.IntegerField(),
        ),
    ]
