# Generated by Django 3.0.5 on 2023-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20230905_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=50)),
                ('selectmodel', models.CharField(max_length=200)),
                ('selecttype', models.CharField(max_length=200)),
                ('refrence', models.CharField(max_length=55)),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('features', models.CharField(max_length=25)),
                ('value', models.IntegerField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
