# Generated by Django 3.0.5 on 2023-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_carbooking_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='price',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
