# Generated by Django 3.0.5 on 2023-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20230905_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitle', models.CharField(max_length=25)),
                ('Features', models.CharField(max_length=25)),
                ('Value', models.IntegerField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selectcarbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbrand', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='model',
        ),
        migrations.DeleteModel(
            name='type',
        ),
        migrations.RenameField(
            model_name='carbooking',
            old_name='DueDate',
            new_name='Duedate',
        ),
        migrations.RenameField(
            model_name='carbooking',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
        migrations.RenameField(
            model_name='carbooking',
            old_name='selectmodel',
            new_name='Selectcar',
        ),
        migrations.RenameField(
            model_name='carbooking',
            old_name='selecttype',
            new_name='selectfeatures',
        ),
    ]
