# Generated by Django 3.0.5 on 2023-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carbrand', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=25)),
                ('Phonenumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=50)),
                ('Selectcar', models.CharField(max_length=200)),
                ('selectfeatures', models.CharField(max_length=200)),
                ('Refrence', models.CharField(max_length=55)),
                ('Address', models.TextField()),
                ('Paymentstatus', models.CharField(blank=True, max_length=55, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=55, null=True)),
                ('Duedate', models.DateTimeField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='rentingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartitle', models.CharField(max_length=50)),
                ('Features', models.CharField(max_length=50)),
                ('Value', models.IntegerField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
