# Generated by Django 3.0.5 on 2023-09-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='timestamp',
        ),
    ]
