# Generated by Django 3.0.5 on 2023-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20230908_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='Title',
            new_name='title',
        ),
    ]
