# Generated by Django 3.0.5 on 2023-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_auto_20230908_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Title',
            field=models.CharField(max_length=1000),
        ),
    ]
