# Generated by Django 3.0.5 on 2023-09-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20230908_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
